"""Serialises a config dict -- the same shape `config.parse_yaml_subset()`
returns -- back out to YAML text, in the exact restricted subset
`config.py`'s hand-rolled parser understands (see that module's docstring
for the subset's rules).

Why a separate module from config.py: reading/validating and writing are
different concerns, and config.py's docstring is already dense describing
what it accepts -- it shouldn't also have to describe what gets written.

The correctness bar is round-tripping, not prettiness:

    parse_yaml_subset(write_config_text(parse_yaml_subset(x))) == parse_yaml_subset(x)

for any config text `x` the parser accepts. That means this module only
ever serialises the keys actually PRESENT in the dict it's given -- it
never invents a default for a missing key, and never silently drops a key
it doesn't recognise (unknown keys fall through to a generic scalar/list
writer). Filling in defaults is config.py's `build_config()` job, done
BEFORE a caller gets here; webui.py always validates through build_config()
first and only calls write_config() with something build_config() accepted.

The parser throws comments away, so nothing written here can be preserved
from the file it's replacing. Instead this module re-emits a standard
header plus per-field comments, reusing the wording from
config.example.yaml, so a config saved through the web UI stays exactly as
self-documenting as a hand-written one.
"""

import os
import tempfile
from typing import Any, Dict, List, Optional


class ConfigWriteError(Exception):
    """Raised when a value cannot be represented in this YAML subset."""


# ---------------------------------------------------------------------------
# Low-level scalar/list rendering
# ---------------------------------------------------------------------------


def _yaml_scalar(value: Any) -> str:
    """Render one scalar in a form `config.py`'s parser reads back exactly.

    Booleans and ints are written bare; everything else is double-quoted.
    `None` is written as nothing at all -- `key:` with a blank value is
    exactly what `_parse_scalar("")` reads back as None.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if value is None:
        return ""
    text = str(value)
    # The parser strips one matching pair of quotes and does no escaping
    # (see config.py's _parse_scalar) -- a literal quote or backslash
    # cannot round-trip through this subset. Refuse rather than emit a
    # file the parser would misread.
    if '"' in text or "\\" in text:
        raise ConfigWriteError(
            f"value {text!r} contains a double-quote or backslash, which this "
            "YAML subset cannot write and read back safely"
        )
    return f'"{text}"'


def _yaml_flow_list(items: List[Any]) -> str:
    return "[" + ", ".join(_yaml_scalar(v) for v in items) + "]"


def _render_value(value: Any) -> str:
    if isinstance(value, list):
        return _yaml_flow_list(value)
    if isinstance(value, dict):
        raise ConfigWriteError("flow mappings are not supported by this YAML subset")
    return _yaml_scalar(value)


def _comment_block(lines: List[str], indent: int) -> List[str]:
    pad = " " * indent
    return [f"{pad}# {line}" if line else f"{pad}#" for line in lines]


def _field_line(key: str, value: Any, indent: int, trailing_comment: Optional[str] = None) -> str:
    pad = " " * indent
    line = f"{pad}{key}: {_render_value(value)}"
    if trailing_comment:
        line += f"   # {trailing_comment}"
    return line


# ---------------------------------------------------------------------------
# Field wording -- reused verbatim (or, for destinations, abbreviated to a
# one-line trailing comment) from config.example.yaml.
# ---------------------------------------------------------------------------

_HEADER = [
    "meshwars-bot config. Generated by the built-in web UI -- hand edits are",
    "fine, but will be overwritten, comments included, the next time a config",
    "is saved through the UI. See config.example.yaml for the full narrative",
    "documentation of every field.",
    "",
    "Parsed by meshwars_bot/config.py's small, hand-rolled YAML-subset parser",
    "(there is no PyYAML dependency here) -- see that file's docstring for",
    "exactly what YAML features it supports. Keep this file within that",
    "subset: plain 2-space indentation, quoted strings, bare ints/bools, and",
    "inline `[...]` lists of scalars only.",
]

_FEED_BASE_URL_COMMENT = [
    "Base URL of the MeshWars instance whose public announcement feed this",
    "bot polls. The bot GETs {base_url}/api/v1/announcements.",
]
_FEED_API_KEY_COMMENT = [
    "Optional API key sent as the X-API-Key header. Keyless polling works;",
    "an API key just raises your rate limit. Empty string = keyless.",
]
_FEED_TIMEOUT_COMMENT = ["HTTP request timeout, in seconds, for each poll."]

_STATE_PATH_COMMENT = [
    "Where the bot's durable state (feed cursor, ETag, and the record of which",
    "announcements have already been sent to which destination) is written.",
    "Must be writable, and must survive restarts -- this is what makes the",
    "first-run \"fast-forward, send nothing\" behaviour possible.",
]

_WEB_COMMENT = [
    "The built-in web config UI (this file can also be hand-edited directly --",
    "the UI is optional). Binds with NO authentication, so bind_host should",
    "stay on a trusted LAN. A config saved through the UI takes effect on the",
    "NEXT poll cycle without restarting the process.",
]

_DESTINATIONS_HEADER_COMMENT = [
    "One entry per mesh channel/radio you want announcements relayed to. A",
    "single feed can fan out to many destinations, each with its own filters.",
    "",
    "transport: meshcore | meshtastic | dryrun -- only meaningful once a real",
    "  transport exists for it; dry_run (below) is what actually gates sending.",
    "host / port / channel: connection details for the (future) real",
    "  transport. Unused while dry_run is true.",
    "board: mc/meshcore or mt/meshtastic -- an announcement is only relayed",
    "  here if its board matches.",
    "dry_run: safety switch. Defaults to true when absent. While true,",
    "  nothing transmits -- messages only go to the local dry-run log and",
    "  stdout. Only flip to false once a real transport exists (today that",
    "  raises NotImplementedError on purpose).",
    "text_budget: bytes the feed fits this destination's announcement text",
    "  to, clamped to 20-1000. Each distinct text_budget across all",
    "  destinations costs one extra feed request per poll cycle.",
    "kinds: explicit allow-list of announcement kinds relayed here.",
    "net_ids: explicit allow-list of net IDs whose net-tied announcements are",
    "  relayed here. EMPTY ([]) means NO net announcements reach this",
    "  destination -- opt-in, not a wildcard.",
    "send_after / send_before: optional 24h \"HH:MM\" send window, in local",
    "  time. Both absent (the default) means relay immediately, exactly as",
    "  before. An announcement arriving outside the window is held (durably",
    "  -- it survives a restart) and relayed at the first poll that falls",
    "  inside the window. A window may wrap midnight (send_after later than",
    "  send_before, e.g. \"22:00\"/\"06:00\").",
    "timezone: IANA zone name (e.g. \"America/Boise\") send_after/send_before",
    "  are interpreted in. Absent -- defaults to the bot host's own local",
    "  timezone.",
]

# Destination field order, matching config.example.yaml, with a short
# trailing inline comment per field (the full explanation lives once, in
# _DESTINATIONS_HEADER_COMMENT above, rather than repeated per entry).
_DESTINATION_FIELD_ORDER = [
    ("name", None),
    ("transport", "meshcore | meshtastic | dryrun"),
    ("host", None),
    ("port", None),
    ("channel", None),
    ("board", "mc/meshcore or mt/meshtastic"),
    ("dry_run", "safety switch -- true means nothing transmits"),
    ("text_budget", "bytes, clamped 20-1000"),
    ("kinds", "announcement kinds relayed here"),
    ("net_ids", "opt-in net allow-list -- [] means no net announcements"),
    ("send_after", "HH:MM 24h -- hold until this local time; absent = relay immediately"),
    ("send_before", "HH:MM 24h -- hold after this local time"),
    ("timezone", "IANA zone for send_after/send_before; absent = host local time"),
]


def _write_known_fields(
    out: List[str], mapping: Dict[str, Any], order: List[str], indent: int, comments: Dict[str, List[str]]
) -> List[str]:
    """Emit fields in `order` that are present in `mapping`, each preceded
    by its comment block, then any remaining keys not in `order` as plain
    (uncommented) lines so nothing present in the input is ever dropped."""
    remaining = dict(mapping)
    for key in order:
        if key not in mapping:
            continue
        comment = comments.get(key)
        if comment:
            out.extend(_comment_block(comment, indent))
        out.append(_field_line(key, mapping[key], indent))
        del remaining[key]
    for key, value in remaining.items():
        out.append(_field_line(key, value, indent))
    return out


def _write_destination(out: List[str], dest: Dict[str, Any]) -> None:
    name = dest.get("name", "")
    out.append(f"  # --- {name} ---" if name else "  # ---")
    remaining = dict(dest)
    first = True
    for key, short_comment in _DESTINATION_FIELD_ORDER:
        if key not in dest:
            continue
        prefix = "  - " if first else "    "
        first = False
        out.append(f"{prefix}{key}: {_render_value(dest[key])}" + (f"   # {short_comment}" if short_comment else ""))
        del remaining[key]
    for key, value in remaining.items():
        prefix = "  - " if first else "    "
        first = False
        out.append(f"{prefix}{key}: {_render_value(value)}")


def write_config_text(raw: Dict[str, Any]) -> str:
    """Render `raw` (a dict shaped like config.parse_yaml_subset()'s output)
    as YAML text in config.py's supported subset. Only keys present in
    `raw` (and, within `feed`/`web`/each destination, only keys present in
    THOSE sub-dicts) are written."""
    out: List[str] = []
    out.extend(_comment_block(_HEADER, 0))
    out.append("")

    if "feed" in raw:
        if not raw["feed"]:
            # parse_yaml_subset() can never actually produce an empty-but-
            # present dict here -- `feed:` with nothing under it parses as
            # None, not {} (see config.py's _parse_mapping) -- and flow
            # mappings (`feed: {}`) aren't supported by that parser at all.
            # So this can only happen from a hand-built raw dict, and there
            # is no way to write it that round-trips; fail loudly instead
            # of silently writing something parse_yaml_subset reads back
            # differently.
            raise ConfigWriteError("'feed' is present but empty -- cannot round-trip an empty mapping in this YAML subset")
        out.append("feed:")
        _write_known_fields(
            out,
            raw["feed"],
            ["base_url", "api_key", "timeout_seconds"],
            2,
            {
                "base_url": _FEED_BASE_URL_COMMENT,
                "api_key": _FEED_API_KEY_COMMENT,
                "timeout_seconds": _FEED_TIMEOUT_COMMENT,
            },
        )
        out.append("")

    if "state_path" in raw:
        out.extend(_comment_block(_STATE_PATH_COMMENT, 0))
        out.append(_field_line("state_path", raw["state_path"], 0))
        out.append("")

    if "web" in raw:
        if not raw["web"]:
            raise ConfigWriteError("'web' is present but empty -- cannot round-trip an empty mapping in this YAML subset")
        out.extend(_comment_block(_WEB_COMMENT, 0))
        out.append("web:")
        _write_known_fields(
            out, raw["web"], ["enabled", "bind_host", "bind_port"], 2, {}
        )
        out.append("")

    if "destinations" in raw:
        out.extend(_comment_block(_DESTINATIONS_HEADER_COMMENT, 0))
        destinations = raw["destinations"]
        if not destinations:
            # An empty block sequence (`destinations:` with nothing under
            # it) parses back as None, not `[]` -- the inline flow form is
            # the only way to round-trip an explicitly empty list.
            out.append("destinations: []")
        else:
            out.append("destinations:")
            for dest in destinations:
                _write_destination(out, dest)
        out.append("")

    # Anything at the top level this module doesn't specifically know about
    # (there shouldn't be any, given build_config()'s validation runs
    # first, but never silently drop it).
    known_top = {"feed", "state_path", "web", "destinations"}
    for key, value in raw.items():
        if key in known_top:
            continue
        out.append(_field_line(key, value, 0))

    text = "\n".join(out).rstrip("\n") + "\n"
    return text


def write_config(raw: Dict[str, Any], path: str) -> None:
    """Atomically write `raw` as YAML to `path` (temp file + os.replace, same
    pattern as state.py's save_state -- a crash mid-write must never leave a
    half-written config file)."""
    text = write_config_text(raw)
    directory = os.path.dirname(os.path.abspath(path)) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".meshwars-bot-config-", suffix=".tmp", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise
